services:
  - type: web
    name: ai-job-application-assistant-api
    env: node
    rootDir: Backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://hassan2163.github.io
